config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :configurations
  resources :categories
  resources :payments
  resources :expenses
  resources :revenues
  
  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  has_many :expense_payments, dependent: :destroy
  has_many :revenue_payments, dependent: :destroy
  has_many :expenses, through: :expense_payments
  has_many :revenues, through: :revenue_payments

  validates_presence_of :payday, :status, :user

  accepts_nested_attributes_for :expense_payments, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :revenue_payments, reject_if: :all_blank, allow_destroy: true

  attribute :status, :integer, default: Proc.new { Payment.statuses["aberto"] }

  after_save :total_value

  enum status: {
    aberto: 0,
    concluido: 1
  }

  def expenses_fixed_not_used
    Expense.where(user: user).where(fixed: true).where.not(id: [expense_ids])
  end

  def balance_in_percentage
    salary = ::Configuration.where(user: user).last.try(:salary).to_f
    balance = ((self.value.to_f * 100)/salary).round(2)
  end

  private

  def total_value
    self.value = total_expense_payments - total_revenue_payments
    self.update_column(:value, self.value)
  end

  def total_expense_payments
    self.expense_payments.inject(0){|sum, ep| sum + ep.value }
  end

  def total_revenue_payments
    self.revenue_payments.inject(0){|sum, ep| sum + ep.value }
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.where(user: current_user).order(payday: :desc).paginate(:page => params[:page], :per_page => 5)
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
    @payment.user = current_user
    
    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Pagamento foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Pagamento foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Pagamento foi excluído com sucesso' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:payday, :status, :note,
        expense_payments_attributes: [:id, :expense_id, :value, :_destroy ],
        revenue_payments_attributes: [:id, :revenue_id, :value, :_destroy ])
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_expense_payment_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="input-field col s7">
      <%= f.label :expense, class: 'active' %>
      <%= f.select :expense_id, 
          options_from_collection_for_select(Expense.where(user: current_user).order(:name), :id, :name, f.object.expense_id ),
          { :include_blank => 'Selecione' }, { :class => 'browser-default' } %>
    </div>
    <div class="input-field col s3">
      <%= f.label :value, class: 'active' %>
      <%= f.number_field :value, step: :any %>
    </div>
    <div class="input-field col s2">  
      <%= link_to_remove_association(f, class: 'btn-floating btn-small waves-effect waves-light red') do %>
        <i class="material-icons">delete</i>
      <% end %>
    </div>
  </div> 
</div>

app/views/payments/_form.html.erb
<%= form_for(payment) do |f| %>
  <% if payment.errors.any? %>
    <div class="row">
      <div class="col s12 m12">
        <div class="card-panel red">
          <span id="notice" class="white-text">
            <i class="material-icons">error</i>
            <%= pluralize(payment.errors.count, "erro(s)") %> Não foi possível salvar:
            <ul>
              <% payment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </span>
        </div>
      </div>
    </div>
  <% end %>  

  <div class="row">
    <div class="input-field col s6">
      <%= f.label :payday, class: 'active' %>
      <%= f.text_field :payday, class: 'datepicker', value: (f.object.payday.strftime('%d/%m/%Y') if f.object.payday) %>
    </div>

    <div class="input-field col s6">
      <%= f.label :status, class: 'active' %>
      <%= f.select :status, Payment.statuses.keys.to_a, { :include_blank => 'Selecione' }, { :class => 'browser-default' } %>
    </div>  
  </div>

  <div class="row">
    <div class="input-field col s12">
      <i class="material-icons prefix">mode_edit</i>
      <%= f.label :note, class: 'active' %>
      <%= f.text_field :note %>
    </div>
  </div> 

  <% if payment.persisted? && payment.expenses_fixed_not_used.any?%>
  <div class="row">
    <div class="col s12 m12">
      <div class="card-panel yellow lighten-2">
        <span class="black-text" style="display: flex; align-items: center;">
          <i class="material-icons left">info_outline</i>
          <strong>Despesas fixas ainda não pagas:</strong>
        </span>
        <div style="margin-top: 10px; padding-left: 40px;">
          <% payment.expenses_fixed_not_used.each do |expense| %>
            <div class="chip">
              <%= expense.name %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <fieldset>
    <legend><strong>Despesas</strong></legend>
    <div id="expense_payments">
      <span>Adicione suas despesas</span>
      <%= link_to_add_association(f, :expense_payments, class: 'btn-floating btn-small waves-effect waves-light blue') do %>
        <i class="material-icons">add</i>
      <% end %>
      <%= f.fields_for :expense_payments, payment.expense_payments do |expense_payments_fields| %>
        <%= render partial: "expense_payment_fields", locals: { f: expense_payments_fields } %>
      <% end %>
    </div>
  </fieldset>
  <br>

  <fieldset>
    <legend><strong>Receitas</strong></legend>
    <div id="revenue_payments">
      <span>Adicione suas receitas</span>
      <%= link_to_add_association(f, :revenue_payments, class: 'btn-floating btn-small waves-effect waves-light blue') do %>
        <i class="material-icons">add</i>
      <% end %>
      <%= f.fields_for :revenue_payments, payment.revenue_payments do |revenue_payments_fields| %>
        <%= render partial: "revenue_payment_fields", locals: { f: revenue_payments_fields } %>
      <% end %>
    </div>
  </fieldset>
  <br>

  <div class="actions">
    <button class="btn waves-effect waves-light" type="submit" name="action">
      Salvar<i class="material-icons right">save</i>
    </button>
  </div>
  <br>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker();
  });  

</script>

app/views/payments/_revenue_payment_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="input-field col s7">
      <%= f.label :revenue, class: 'active' %>
      <%= f.select :revenue_id, 
          options_from_collection_for_select(Revenue.where(user: current_user).order(:name), :id, :name, f.object.revenue_id ),
          { :include_blank => 'Selecione' }, { :class => 'browser-default' } %>
    </div>
    <div class="input-field col s3">
      <%= f.label :value, class: 'active' %>
      <%= f.number_field :value, step: :any %>
    </div>
    <div class="input-field col s2">  
      <%= link_to_remove_association(f, class: 'btn-floating btn-small waves-effect waves-light red') do %>
        <i class="material-icons">delete</i>
      <% end %>
    </div>
  </div> 
</div>

app/views/payments/edit.html.erb
<h4>Editar Pagamento</h4>

<%= render 'form', payment: @payment %>

<%= link_to 'Visualizar', @payment, class: 'waves-effect waves-light btn blue-grey'%> |
<%= link_to 'Voltar', payments_path, class: 'waves-effect waves-light btn blue-grey' %>

app/views/payments/index.html.erb
<% unless notice.nil? %>
  <div class="row">
    <div class="col s12 m12">
      <div class="card-panel green accent-2">
        <span id="notice" class="black-text">
          <i class="material-icons">check</i>
          <%= notice %>
        </span>
      </div>
    </div>
  </div>
<% end %>

<h4>Pagamentos</h4>

<% if @payments.any? %>
  <table class="striped">
    <thead>
      <tr>
        <th width="25%">Data Pagamento</th>
        <th width="30%">Saldo Total</th>
        <th width="20%">Status</th>
        <th width="25%" colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @payments.each do |payment| %>
        <tr>
          <td><%= payment.payday.to_s(:custom_datetime) %></td>
          <td><%= number_to_currency(payment.value, unit: "R$ ", separator: ",", delimiter: ".") %></td>
          <td><%= badges(payment.status) %></td>
          <td><%= link_to payment, class: 'btn-floating btn-small waves-effect waves-light blue' do %>
                <i class="material-icons">pageview</i>
              <% end %>
          </td>
          <td><%= link_to edit_payment_path(payment), class: 'btn-floating btn-small waves-effect waves-light green' do %>
                <i class="material-icons">edit</i>
              <% end %>
          </td>
          <td><%= link_to payment, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn-floating btn-small waves-effect waves-light red' do %>
                <i class="material-icons">delete</i>
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h6 class="header red-text text-lighten-1 center-align">Não há registros para mostrar</h6>
<% end %>

<div class="right"><h6><strong><%= "#{"Total de registros: " + @payments.count.to_s}" %></h6></strong></div>

<%= will_paginate @payments %>

<br>

<%= link_to 'Novo Pagamento', new_payment_path, class: 'waves-effect waves-light btn' %>

app/views/payments/new.html.erb
<h4>Novo Pagamento</h4>

<%= render 'form', payment: @payment %>

<%= link_to 'Voltar', payments_path, class: 'waves-effect waves-light btn blue-grey' %>

app/views/payments/show.html.erb
<% unless notice.nil? %>
  <div class="row">
    <div class="col s12 m12">
        <div class="card-panel green accent-2">
          <span id="notice" class="black-text">
            <i class="material-icons">check</i>
            <%= notice %>
          </span>
        </div>
    </div>
  </div>
<% end %>

<p>
  <strong>Data Pagamento:</strong>
  <%= @payment.payday.to_s(:custom_datetime) %>
</p>

<p>
  <strong>Status:</strong>
  <%= badges(@payment.status) %>
</p>

<p>
  <strong>Observação:</strong>
  <%= @payment.note %>
</p>

<p>
  <strong>Saldo do Pagamento:</strong>
  <%= @payment.balance_in_percentage.to_s << "%"%>
</p>
<div class="progress">
  <div class="determinate" style="width: <%= @payment.balance_in_percentage.to_s %>%"></div>
</div>

<hr>

<div class="row">
  <div class="col s12 m6">
    <h4 class="header red-text text-lighten-1 center-align">Lista de Despesas</h4>
    <ul class="collection">
      <% @payment.expense_payments.each do |expense_payment| %>
        <li class="collection-item">
          <div class="row" style="margin-bottom: 0;">
            <div class="col s8">
              <span class="title" style="font-weight: bold;"><%= expense_payment.expense.name %></span>
              <p style="margin: 0;"><%= expense_payment.expense.category.name %></p>
            </div>
            <div class="col s4 right-align red-text">
              <%= number_to_currency(expense_payment.value, unit: "R$ ", separator: ",", delimiter: ".") %>
            </div>
            <div class="col s12">
              Fixo: <%= badges_boolean(expense_payment.expense.fixed, :expense) %>
            </div>
          </div>
        </li>
      <% end %>
      <li class="collection-item">
        <div>
          <strong>Valor Total (despesas):</strong>
          <span class="secondary-content red-text bold">
            <strong>
              <%= number_to_currency(@payment.expense_payments.sum(:value), unit: "R$ ", separator: ",", delimiter: ".") %>
            </strong>
          </span>
        </div>
      </li>
    </ul>
  </div>

  <div class="col s12 m6">
    <h4 class="header green-text text-lighten-1 center-align">Lista de Receitas</h4>
    <ul class="collection">
      <% @payment.revenue_payments.each do |revenue_payment| %>
        <li class="collection-item">
          <div class="row" style="margin-bottom: 0;">
            <div class="col s8">
              <span class="title" style="font-weight: bold;"><%= revenue_payment.revenue.name %></span>
              <p style="margin: 0;"><%= revenue_payment.revenue.category.name %></p>
            </div>
            <div class="col s4 right-align green-text">
              <%= number_to_currency(revenue_payment.value, unit: "R$ ", separator: ",", delimiter: ".") %>
            </div>
            <div class="col s12">
              Fixo: <%= badges_boolean(revenue_payment.revenue.fixed, :revenue) %>
            </div>
          </div>
        </li>
      <% end %>
      <li class="collection-item">
        <div>
          <strong>Valor Total (receitas):</strong>
          <span class="secondary-content green-text bold">
            <strong>
              <%= number_to_currency(@payment.revenue_payments.sum(:value), unit: "R$ ", separator: ",", delimiter: ".") %>
            </strong>
          </span>
        </div>
      </li>
    </ul>
  </div>
</div>

<hr>

<p class="right-align bold">
  <strong>Saldo Total (pagamento):</strong>
  <%= number_to_currency(@payment.value, unit: "R$ ", separator: ",", delimiter: ".") %>
</p>

<%= link_to 'Editar', edit_payment_path(@payment), class: 'waves-effect waves-light btn blue-grey' %> |
<%= link_to 'Voltar', payments_path, class: 'waves-effect waves-light btn blue-grey' %>