config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :configurations
  resources :categories
  resources :payments
  resources :expenses
  resources :revenues
  
  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Payapp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <%= favicon_link_tag asset_path('favicon_money.ico') %>
  </head>

  <body>
    <% if user_signed_in? %>
      <ul class="sidenav" id="slide-out">
        <li><%= "#{"Bem Vindo! "}" + current_user.email if user_signed_in? %></li>
        <li><%= link_to 'Dashboard', root_path %></li>
        <li><%= link_to 'Configuração', configurations_path %></li>
        <li><%= link_to 'Categorias', categories_path %></li>
        <li><%= link_to 'Despesas', expenses_path %></li>
        <li><%= link_to 'Receitas', revenues_path %></li>
        <li><%= link_to 'Pagamentos', payments_path %></li>
        <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
      </ul>
      <nav class="indigo blue">
        <div class="nav-wrapper">
          <%= link_to root_path, class: 'brand-logo right' do %>
            <i class="large material-icons">monetization_on</i> Paguei App
          <% end %>
          <a href="#!" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
          <ul id="nav-mobile" class="left hide-on-med-and-down">
            <li><%= link_to 'Dashboard', root_path %></li>
            <li><%= link_to 'Configuração', configurations_path %></li>
            <li><%= link_to 'Categorias', categories_path %></li>
            <li><%= link_to 'Despesas', expenses_path %></li>
            <li><%= link_to 'Receitas', revenues_path %></li>
            <li><%= link_to 'Pagamentos', payments_path %></li>
            <li><i class="material-icons left">account_circle</i><%= "#{"  Bem Vindo! "}" + current_user.email if user_signed_in? %></li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                  Sair<i class="material-icons right">exit_to_app</i>
              <% end %>
            </li>
          </ul>
        </div>
      </nav>

      <div class="container">
        <%= yield %>
      </div>

      <br>
      <footer class="page-footer grey lighten-5">
        <div class="footer-copyright">
          <div class="container black-text">
          © 2018 GOEP SOFTWARE
          </div>
        </div>
      </footer>

    <% else %>
      <%= yield %>
    <% end %>
  </body>

<script type="text/javascript">

</script>
        
</html>